version: '2'
services:
  mariadb:
    image: docker.io/bitnami/mariadb:10.3
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
      - MARIADB_USER=bn_opencart
      - MARIADB_DATABASE=bitnami_opencart
      - MARIADB_ROOT_USER=root
      - MARIADB_ROOT_PASSWORD=root
      - OPENCART_DATABASE_PASSWORD
    volumes:
      - ./persistence/mariadb:/bitnami/mariadb
    networks:
      - backend
  opencart:
    image: docker.io/bitnami/opencart:3
    ports:
      - '80:8080'
      - '443:8443'
    environment:
      - OPENCART_HOST=localhost
      - OPENCART_DATABASE_HOST=mariadb
      - OPENCART_DATABASE_PORT_NUMBER=3306
      - OPENCART_DATABASE_USER=bn_opencart
      - OPENCART_DATABASE_NAME=bitnami_opencart
      - ALLOW_EMPTY_PASSWORD=yes
      - OPENCART_USERNAME=admin
      - OPENCART_PASSWORD=admin
    volumes:
      - ./persistence/opencart:/bitnami/opencart'
      - ./persistence/opencart/storage:/bitnami/opencart_storage/
    depends_on:
      - mariadb
    networks:
      - backend

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: 'opencart-phpmyadmin'
    environment:
      - PMA_HOST=mariadb
      - PMA_PORT=3306
      - PMA_USER=root
      - PMA_PASSWORD=root
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_USER=bn_opencart
      - MYSQL_PASSWORD=''
      - PMA_ARBITRARY=1
    ports:
      - '9090:80'
    volumes:
      - /sessions
    networks:
      - backend
    depends_on:
      - opencart
      - mariadb

networks:
  backend:
    driver: bridge

volumes:
  data: